version: '3'
services:
  napi:

  nginx:
    image: nginx:1.15.8
    ports:
      - 8443:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - public-data:/neams-api/public
      - tmp-data:/neams-api/tmp
    # 別のサービスに依存することを示す。upやdownするときに指定したサービスが先に起動するようになる。
    depends_on:
      - api
    networks:
      - neamsnw
# networkを指定しないといけない
networks:
  neamsnw:
# volumeを指定しないといけない
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:


